// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using desafio_tecnico.Data;

#nullable disable

namespace desafio_tecnico.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260123014053_UpdateDepartamentNameIndexForSoftDelete")]
    partial class UpdateDepartamentNameIndexForSoftDelete
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("desafio_tecnico.Models.Departament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int?>("HigherDepartamentId")
                        .HasColumnType("integer")
                        .HasColumnName("higher_departament_id");

                    b.Property<bool?>("IsDeleted")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("integer")
                        .HasColumnName("manager_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("updatedAt")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("HigherDepartamentId");

                    b.HasIndex("ManagerId")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("\"is_deleted\" = false OR \"is_deleted\" IS NULL");

                    b.ToTable("departaments", null, t =>
                        {
                            t.HasCheckConstraint("chk_higher_departament_not_self", "higher_departament_id IS NULL OR higher_departament_id <> id");
                        });
                });

            modelBuilder.Entity("desafio_tecnico.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("CHAR(11)")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("departament_id");

                    b.Property<bool?>("IsDeleted")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("Rg")
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("rg");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("updatedAt")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("CPF")
                        .IsUnique();

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Rg")
                        .IsUnique();

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("desafio_tecnico.Models.Departament", b =>
                {
                    b.HasOne("desafio_tecnico.Models.Departament", "HigherDepartament")
                        .WithMany("SubDepartaments")
                        .HasForeignKey("HigherDepartamentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("desafio_tecnico.Models.Employee", "Manager")
                        .WithOne("ManagedDepartament")
                        .HasForeignKey("desafio_tecnico.Models.Departament", "ManagerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("HigherDepartament");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("desafio_tecnico.Models.Employee", b =>
                {
                    b.HasOne("desafio_tecnico.Models.Departament", "Departament")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Departament");
                });

            modelBuilder.Entity("desafio_tecnico.Models.Departament", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("SubDepartaments");
                });

            modelBuilder.Entity("desafio_tecnico.Models.Employee", b =>
                {
                    b.Navigation("ManagedDepartament");
                });
#pragma warning restore 612, 618
        }
    }
}
